services:
  - type: web
    name: NimbleGarment-Backend
    runtime: python
    pythonVersion: 3.11
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    envs:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: "False"
