# Generated by Django 6.0.4 on 2026-04-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='dealer.dealer'),
        ),
    ]
