# Generated by Django 6.0.4 on 2026-04-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceProxy',
            fields=[
            ],
            options={
                'db_table': 'attendance',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.attendance',),
        ),
    ]
